# PLEASE STOP!
# DO NOT EDIT THIS FILE
# create a new config.py file in the same directory
# and import this 'sampleconfig.py',
# then extend the Config class
import os

class Config:
    bot_api = os.environ.get("bot_api", None)
    # required for running in webhook mode
    url = os.environ.get("url", None)
    # heroku automatically initializes the $PORT variable
    port = int(os.environ.get("PORT", 5000))
    #
    DEFAULT_VOTE_COUNT = int(os.environ.get("DEFAULT_VOTE_COUNT", "3"))
    DEFAULT_DELETE_TIMEOUT = int(os.environ.get("DEFAULT_DELETE_TIMEOUT", "60"))
    DB_URI = os.environ.get("DB_URI", 'sqlite:///db.db')

